# CodeDeploy will look for this file
version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/chatty-backend
hooks:
    BeforeInstall:
        - location: scripts/before_install.sh
          timeout: 300 # Timeout after 5 mins.
          runas: root
    AfterInstall:
        - location: scripts/after_install.sh
          timeout: 300 # Timeout after 5 mins.
          runas: root
    ApplicationStart:
        - location: scripts/application_start.sh
          timeout: 300 # Timeout after 5 mins.
          runas: root
